services:
  backend:
    image: ai-voice-bot-dev:0.2.1
    ports: 
    - 80:80
    env_file:
    - ".env"
    - ".env-postgres-compose"
    - ".env-qdrant-compose"
    networks:
      - front-tier
      - back-tier
  
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".env-postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - back-tier

  qdrant:
    image: qdrant/qdrant:v1.11.0
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant-data:/qdrant/storage:z
    networks:
      - back-tier
  
networks:
  front-tier: {}
  back-tier: {}

volumes:
  postgres-data: {}
